### ISSUE TITLE
Escaped Characters

### ISSUE THREAD

**Issue by ushahid** [gregdurrett/berkeley-entity#13]
Is there a list of characters which are escaped using \ in the coreference resolution model?

**Comment by gregdurrett** [comment]
I'm not sure what you mean. The data files (in CoNLL format) don't use
backslash to escape anything, and I don't think any backslashes appear. In
the code, backslashes appear as necessary to escape things as is standard
in Java/Scala. Could you be more specific about the issue you're running
into?

If you have a backslash in an input file, that could potentially cause
problems...you may want to replace it with another character and see if
that makes the problem go away.

Greg
